services:
  tiktokmp3-caddy:
    container_name: tiktokmp3-caddy
    image: caddy:2-alpine
    networks:
      - caddy_net
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - tiktokmp3-frontend
      - tiktokmp3-backend
    restart: unless-stopped

  tiktokmp3-backend:
    container_name: tiktokmp3-backend
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    networks:
      - caddy_net
    volumes:
      - ./secrets:/run/secrets:ro
    restart: unless-stopped

  tiktokmp3-frontend:
    container_name: tiktokmp3-frontend
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    networks:
      - caddy_net
    depends_on:
      - tiktokmp3-backend
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:

networks:
  caddy_net:
    external: true
